# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetRooti <- function(Cov, Eye) {
    .Call('_spBFA_GetRooti', PACKAGE = 'spBFA', Cov, Eye)
}

H <- function(Psi, TempCorInd, TimeDist, Nu) {
    .Call('_spBFA_H', PACKAGE = 'spBFA', Psi, TempCorInd, TimeDist, Nu)
}

SpEXP <- function(Rho, SpDist, M) {
    .Call('_spBFA_SpEXP', PACKAGE = 'spBFA', Rho, SpDist, M)
}

bfa_sp_Rcpp <- function(DatObj_List, HyPara_List, MetrObj_List, Para_List, DatAug_List, McmcObj_List, RawSamples, Interactive) {
    .Call('_spBFA_bfa_sp_Rcpp', PACKAGE = 'spBFA', DatObj_List, HyPara_List, MetrObj_List, Para_List, DatAug_List, McmcObj_List, RawSamples, Interactive)
}

Play <- function(X) {
    .Call('_spBFA_Play', PACKAGE = 'spBFA', X)
}

GetLStarJ <- function(U, Weights, K, M, O) {
    .Call('_spBFA_GetLStarJ', PACKAGE = 'spBFA', U, Weights, K, M, O)
}

GetLambda <- function(Theta, Xi, K, M, O) {
    .Call('_spBFA_GetLambda', PACKAGE = 'spBFA', Theta, Xi, K, M, O)
}

GetWeights <- function(Alpha, K, M, L, O) {
    .Call('_spBFA_GetWeights', PACKAGE = 'spBFA', Alpha, K, M, L, O)
}

GetlogWeights <- function(Alpha, K, M, L, O) {
    .Call('_spBFA_GetlogWeights', PACKAGE = 'spBFA', Alpha, K, M, L, O)
}

CholInv <- function(Cov) {
    .Call('_spBFA_CholInv', PACKAGE = 'spBFA', Cov)
}

Inv3 <- function(A) {
    .Call('_spBFA_Inv3', PACKAGE = 'spBFA', A)
}

makeSymm <- function(A) {
    .Call('_spBFA_makeSymm', PACKAGE = 'spBFA', A)
}

